#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-publish a monthly "Daily" post for this static site.

Defaults:
- Source images: /Users/chengqian/Documents/colo/img/YYYY-MM/
- Publish month: previous month (so running on the 1st summarizes last month)
- Publish date: today
- Cover: cover.* if present, else most recently modified image
- Text: generated by OpenClaw local agent (openclaw agent --local)

Usage:
  python3 scripts/publish_month.py
  python3 scripts/publish_month.py --month 2025-03 --date 2025-04-01
  python3 scripts/publish_month.py --no-openclaw
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import html
import json
import os
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_ROOT = "/Cola-Sprite.github.io/"
SOURCE_BASE = Path("/Users/chengqian/Documents/colo/img")
OPENCLAW = Path("/opt/homebrew/bin/openclaw")
OSXPHOTOS = Path("/opt/homebrew/bin/osxphotos")

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}

CN_MONTHS = [
    "一月", "二月", "三月", "四月", "五月", "六月",
    "七月", "八月", "九月", "十月", "十一月", "十二月",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--month", help="Target month in YYYY-MM (default: previous month).")
    parser.add_argument("--date", help="Publish date YYYY-MM-DD (default: today).")
    parser.add_argument("--no-openclaw", action="store_true", help="Skip OpenClaw and use fallback text.")
    parser.add_argument("--openclaw-path", default=str(OPENCLAW), help="Path to openclaw binary.")
    parser.add_argument("--photos", action="store_true", help="Pull random photos from Photos.app for the month.")
    parser.add_argument("--photos-count", type=int, default=7, help="How many photos to export from Photos.app.")
    parser.add_argument("--photos-library", default="", help="Optional Photos library path.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing post if present.")
    parser.add_argument("--push", action="store_true", help="Auto git add/commit/push.")
    parser.add_argument("--commit-message", default="", help="Custom git commit message.")
    parser.add_argument("--dry-run", action="store_true", help="Do not write files.")
    return parser.parse_args()


def month_previous(today: dt.date) -> Tuple[int, int]:
    first = today.replace(day=1)
    prev_last = first - dt.timedelta(days=1)
    return prev_last.year, prev_last.month


def parse_month(month_str: Optional[str]) -> Tuple[int, int]:
    if not month_str:
        return month_previous(dt.date.today())
    m = re.fullmatch(r"(\d{4})-(\d{2})", month_str)
    if not m:
        raise ValueError("Month must be in YYYY-MM format.")
    return int(m.group(1)), int(m.group(2))


def parse_date(date_str: Optional[str]) -> dt.date:
    if not date_str:
        return dt.date.today()
    return dt.datetime.strptime(date_str, "%Y-%m-%d").date()


def list_images(src_dir: Path) -> List[Path]:
    if not src_dir.exists():
        return []
    images = []
    for p in src_dir.iterdir():
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS:
            images.append(p)
    return sorted(images)


def month_date_range(year: int, month: int) -> Tuple[dt.date, dt.date]:
    start = dt.date(year, month, 1)
    if month == 12:
        end = dt.date(year + 1, 1, 1) - dt.timedelta(days=1)
    else:
        end = dt.date(year, month + 1, 1) - dt.timedelta(days=1)
    return start, end


def extract_uuids(data) -> List[str]:
    uuids = []
    if isinstance(data, dict):
        if isinstance(data.get("uuid"), str):
            uuids.append(data["uuid"])
        for value in data.values():
            uuids.extend(extract_uuids(value))
    elif isinstance(data, list):
        for item in data:
            uuids.extend(extract_uuids(item))
    return uuids


def clear_dir_images(dir_path: Path) -> None:
    if not dir_path.exists():
        return
    for p in dir_path.iterdir():
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS:
            p.unlink()


def convert_images_to_jpeg(dir_path: Path) -> None:
    sips = shutil.which("sips")
    if not sips:
        return
    for p in dir_path.iterdir():
        if not p.is_file():
            continue
        if p.suffix.lower() in {".jpg", ".jpeg"}:
            continue
        if p.suffix.lower() not in IMAGE_EXTS:
            continue
        target = p.with_suffix(".jpg")
        if target.exists():
            target = p.with_name(f"{p.stem}-converted.jpg")
        subprocess.run(
            [sips, "-s", "format", "jpeg", str(p), "--out", str(target)],
            check=False,
            capture_output=True,
            text=True,
        )
        try:
            p.unlink()
        except FileNotFoundError:
            pass
        try:
            os.chmod(target, 0o644)
        except Exception:
            pass


def detect_photos_library(osxphotos: str) -> str:
    try:
        result = subprocess.run(
            [osxphotos, "list", "--json"],
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except Exception:
        return ""
    if not result.stdout:
        return ""
    try:
        data = json.loads(result.stdout)
    except Exception:
        return ""
    last_lib = data.get("last_library")
    if isinstance(last_lib, str) and last_lib:
        return last_lib
    libs = data.get("photo_libraries")
    if isinstance(libs, list) and libs:
        return libs[0]
    return ""


def export_random_photos_from_photos(
    year: int,
    month: int,
    dest_dir: Path,
    count: int,
    library_path: str = "",
) -> bool:
    osxphotos = shutil.which("osxphotos")
    if not osxphotos:
        try:
            user_base = subprocess.run(
                [sys.executable, "-m", "site", "--user-base"],
                check=False,
                capture_output=True,
                text=True,
            ).stdout.strip()
        except Exception:
            user_base = ""
        candidates = []
        if user_base:
            candidates.append(str(Path(user_base) / "bin" / "osxphotos"))
        candidates.append(str(Path.home() / ".local" / "bin" / "osxphotos"))
        candidates.append(str(OSXPHOTOS))
        for cand in candidates:
            if cand and Path(cand).exists():
                osxphotos = cand
                break
    if not osxphotos or not Path(osxphotos).exists():
        print("ERROR: osxphotos CLI not found. Install with `python3 -m pip install --user osxphotos`.")
        return False

    if not library_path:
        library_path = detect_photos_library(osxphotos)

    start, end = month_date_range(year, month)
    from_date = start.isoformat()
    to_date = end.isoformat()

    query_cmd = [
        osxphotos,
        "query",
        "--from-date",
        from_date,
        "--to-date",
        to_date,
        "--only-photos",
        "--json",
    ]
    if library_path:
        query_cmd.extend(["--library", library_path])
    try:
        result = subprocess.run(
            query_cmd,
            check=False,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except Exception as exc:
        print(f"ERROR: osxphotos query failed: {exc}")
        return False
    if not result.stdout:
        err = (result.stderr or "").strip()
        if err:
            print(f"ERROR: osxphotos query error: {err}")
        else:
            print("ERROR: osxphotos query returned no data.")
        return False
    try:
        data = json.loads(result.stdout)
    except Exception as exc:
        print(f"ERROR: Failed to parse osxphotos JSON: {exc}")
        return False

    uuids = list(dict.fromkeys(extract_uuids(data)))
    if not uuids:
        print("ERROR: No photos found for the month in Photos.app.")
        return False

    count = max(1, count)
    pick = random.sample(uuids, min(count, len(uuids)))

    dest_dir.mkdir(parents=True, exist_ok=True)
    clear_dir_images(dest_dir)

    export_cmd = [osxphotos, "export", "--only-photos"]
    for uid in pick:
        export_cmd.extend(["--uuid", uid])
    if library_path:
        export_cmd.extend(["--library", library_path])
    export_cmd.append(str(dest_dir))
    try:
        subprocess.run(
            export_cmd,
            check=False,
            capture_output=True,
            text=True,
            timeout=300,
        )
    except Exception as exc:
        print(f"ERROR: osxphotos export failed: {exc}")
        return False

    # Remove osxphotos export db if created
    export_db = dest_dir / ".osxphotos_export.db"
    if export_db.exists():
        try:
            export_db.unlink()
        except Exception:
            pass

    convert_images_to_jpeg(dest_dir)
    return True


def image_size_sips(path: Path) -> Optional[Tuple[int, int]]:
    sips = shutil.which("sips")
    if not sips:
        return None
    try:
        result = subprocess.run(
            [sips, "-g", "pixelWidth", "-g", "pixelHeight", str(path)],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except Exception:
        return None
    width = height = None
    for line in (result.stdout or "").splitlines():
        if "pixelWidth" in line:
            width = int(line.strip().split()[-1])
        if "pixelHeight" in line:
            height = int(line.strip().split()[-1])
    if width and height:
        return width, height
    return None


def cover_score(path: Path) -> float:
    name = path.stem.lower()
    score = 0.0
    if name.startswith("cover"):
        score += 1000.0
    if any(k in name for k in ["sky", "sunset", "sea", "mountain", "city", "street", "park"]):
        score += 50.0
    size = image_size_sips(path)
    if size:
        w, h = size
        ratio = w / h if h else 1.0
        # Favor landscape ratio
        if 1.2 <= ratio <= 2.4:
            score += 200.0
        score += (w * h) / 1_000_000.0
    else:
        # Fallback to file size
        score += path.stat().st_size / 1_000_000.0
    # Recent files slight bonus
    score += path.stat().st_mtime / 1_000_000_000.0
    return score


def pick_cover(images: List[Path]) -> Optional[Path]:
    if not images:
        return None
    return max(images, key=cover_score)


def ensure_copy_images(images: List[Path], dst_dir: Path, dry_run: bool) -> None:
    if dry_run:
        return
    dst_dir.mkdir(parents=True, exist_ok=True)
    for img in images:
        shutil.copy2(img, dst_dir / img.name)
        os.chmod(dst_dir / img.name, 0o644)


def is_valid_template(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return False
    if "<title>" not in text or "</title>" not in text:
        return False
    return True


def find_latest_post() -> Path:
    posts = []
    for p in REPO_ROOT.rglob("index.html"):
        rel = p.relative_to(REPO_ROOT).as_posix()
        m = re.match(r"(\d{4})/(\d{2})/(\d{2})/[^/]+/index.html$", rel)
        if not m:
            continue
        y, mo, d = map(int, m.groups())
        if is_valid_template(p):
            posts.append((dt.date(y, mo, d), p))
    if not posts:
        raise RuntimeError("No existing posts found to use as template.")
    posts.sort(key=lambda x: x[0], reverse=True)
    return posts[0][1]


def post_link_from_path(path: Path) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    m = re.match(r"(\d{4})/(\d{2})/(\d{2})/([^/]+)/index.html$", rel)
    if not m:
        return ""
    y, mo, d, slug = m.groups()
    return f"{SITE_ROOT}{y}/{mo}/{d}/{slug}/"


def extract_first(pattern: str, text: str, default: str = "") -> str:
    m = re.search(pattern, text, re.DOTALL)
    return m.group(1) if m else default


def openclaw_generate(prompt: str, openclaw_path: str) -> Optional[Dict]:
    if not Path(openclaw_path).exists():
        return None
    try:
        result = subprocess.run(
            [openclaw_path, "agent", "--local", "--message", prompt],
            check=False,
            capture_output=True,
            text=True,
            timeout=600,
        )
    except Exception:
        return None

    output = (result.stdout or "").strip()
    if not output:
        return None

    # Try to extract JSON from output
    start = output.find("{")
    end = output.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(output[start : end + 1])
    except Exception:
        return None


def encode_image_base64(image_path: Path) -> str:
    """Encode image to base64 string."""
    try:
        with open(image_path, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    except Exception:
        return ""


def analyze_images(image_paths: List[Path], openclaw_path: str) -> str:
    """Use vision model to analyze images and return descriptions."""
    if not image_paths or not Path(openclaw_path).exists():
        return ""

    # Check if openclaw agent supports --image
    try:
        help_out = subprocess.run(
            [openclaw_path, "agent", "--help"],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if "--image" not in (help_out.stdout or ""):
            return ""
    except Exception:
        return ""
    
    # Only analyze first 4 images to keep prompt size reasonable
    images_to_analyze = image_paths[:4]
    
    descriptions = []
    for img in images_to_analyze:
        b64 = encode_image_base64(img)
        if not b64:
            continue
        
        # Use openclaw agent with vision to describe the image
        vision_prompt = f"describe this image in one short Chinese sentence (within 20 words). Focus on: what is in the image, the mood/vibe, colors. Just describe, don't interpret. Image file: {img.name}"
        
        try:
            result = subprocess.run(
                [openclaw_path, "agent", "--local", "--message", vision_prompt, "--image", f"data:image/jpeg;base64,{b64}"],
                check=False,
                capture_output=True,
                text=True,
                timeout=60,
            )
            desc = (result.stdout or "").strip()
            if desc and len(desc) < 200:
                descriptions.append(f"- {img.name}: {desc}")
        except Exception:
            continue
    
    if descriptions:
        return "\n图片内容分析：\n" + "\n".join(descriptions)
    return ""


def fallback_content(year: int, month_cn: str) -> Dict:
    return {
        "h1": f"{month_cn}：日常与小确幸～",
        "quote": "“日子缓缓，温柔自来。” —— 佚名",
        "intro": f"{year}年的{month_cn}，我们把节奏放慢了一点，把心放稳了一点。",
        "section1": {
            "title": "🌿 春天的信号",
            "text": "天气逐渐转暖，风也变得柔和。我们在忙碌里留出一点小空隙，去感受生活的细微变化。",
        },
        "section2": {
            "title": "🍲 厨房的小欢喜",
            "text": "一顿简单的家常饭，也能让一天变得很踏实。热气升起的时候，心也跟着安静下来。",
        },
        "section3": {
            "title": "🚶 傍晚散步",
            "text": "下班后的路，走得不快，却很安心。我们聊着琐事，也聊着新的小目标。",
        },
        "section4": {
            "title": "📝 小小计划",
            "bullets": [
                "每周固定两次运动，保持轻松但稳定。",
                "尽量早睡早起，给身体一点缓冲。",
                "把每个月的日常继续记录下来。",
            ],
        },
        "section5": {
            "title": "✨ 小确幸清单",
            "text": "一杯热饮、一段散步、一张照片，都是这个月的小确幸。",
        },
        "section6": {
            "title": "🧺 生活碎片",
            "text": "把零碎的快乐收好，等忙碌的时候翻出来看看。",
        },
        "closing": "愿我们在新的一个月里，依旧被温柔和热爱包围。",
    }


def build_prompt(year: int, month_cn: str, title: str, image_names: List[str], image_descriptions: str = "") -> str:
    image_list = "\n".join(f"- {name}" for name in image_names[:8])
    desc_section = f"\n{image_descriptions}\n" if image_descriptions else ""
    return (
        "你是写作爱人日常的中文博客作者。请写一篇温暖、细腻、生活化的月度记录。\n"
        f"标题主题：{title}\n"
        f"月份：{year}年{month_cn}\n"
        "可参考的图片（图片内容和风格描述）：\n"
        f"{image_list}\n"
        f"{desc_section}"
        "请根据上述图片的真实内容来写，确保文案与图片氛围匹配。\n"
        "\n"
        "请严格输出 JSON，不要包含其它文字。JSON 格式如下：\n"
        "{\n"
        '  "h1": "三月：xxxx～",\n'
        '  "quote": "一句话 —— 作者",\n'
        '  "intro": "2-3 句话的引入",\n'
        '  "section1": {"title": "🌿 春天的信号", "text": "..."},\n'
        '  "section2": {"title": "🍲 厨房的小欢喜", "text": "..."},\n'
        '  "section3": {"title": "🚶 傍晚散步", "text": "..."},\n'
        '  "section4": {"title": "📝 小小计划", "bullets": ["...", "...", "..."]},\n'
        '  "section5": {"title": "✨ 小确幸清单", "text": "..."},\n'
        '  "section6": {"title": "🧺 生活碎片", "text": "..."},\n'
        '  "closing": "结语 1-2 句"\n'
        "}\n"
        "要求：语言自然、温柔，不要提到AI或提示词。文案必须与图片内容和氛围匹配。"
    )


def safe_text(s: str) -> str:
    return html.escape(s, quote=False).replace("\n", " ").strip()


def safe_id(s: str) -> str:
    s = re.sub(r"[<>\"']", "", s)
    return s.strip()


def build_image_captions(images: List[Path]) -> Dict[str, str]:
    keyword_map = {
        "coffee": "咖啡香气",
        "morning": "清晨的光",
        "sunset": "日落晚霞",
        "park": "公园散步",
        "book": "安静阅读",
        "cozy": "温暖角落",
        "cover": "本月封面",
        "food": "家常味道",
        "dinner": "晚餐时刻",
        "breakfast": "早餐时间",
        "lunch": "午间片刻",
        "night": "夜色",
        "street": "街角",
        "sky": "天空",
        "rain": "雨后",
        "snow": "冬日",
        "flower": "花开",
        "sea": "海风",
        "mountain": "远山",
    }
    captions: Dict[str, str] = {}
    for img in images:
        stem = img.stem.lower()
        tokens = re.split(r"[^a-z0-9]+", stem)
        picked = []
        for t in tokens:
            if t in keyword_map and keyword_map[t] not in picked:
                picked.append(keyword_map[t])
            if len(picked) >= 2:
                break
        if not picked:
            captions[img.name] = "这一刻"
        else:
            captions[img.name] = " · ".join(picked)
    return captions


def build_photo_wall(img_rel_paths: List[str], captions: Dict[str, str]) -> str:
    if not img_rel_paths:
        return ""
    cols = 3
    rows = [img_rel_paths[i : i + cols] for i in range(0, len(img_rel_paths), cols)]
    html_rows = []
    for row in rows:
        cells = []
        for src in row:
            name = Path(src).name
            cap = captions.get(name, "")
            cap_html = f"<figcaption>{cap}</figcaption>" if cap else ""
            cells.append(f'<td><figure><img src="{src}" alt="{cap}" style="zoom:45%;" />{cap_html}</figure></td>')
        while len(cells) < cols:
            cells.append("<td></td>")
        html_rows.append("<tr>" + "".join(cells) + "</tr>")
    return "<table><thead><tr><th>回忆墙</th><th></th><th></th></tr></thead><tbody>" + "".join(html_rows) + "</tbody></table>"


def build_article_html(content: Dict, img_rel_paths: List[str], captions: Dict[str, str]) -> str:
    # Ensure we have at least 4 images to place
    imgs = (img_rel_paths + img_rel_paths[:6])[:6]
    img_a, img_b, img_c, img_d, img_e, img_f = (imgs + imgs[:6])[:6]

    quote = content.get("quote", "")
    quote_text, quote_author = quote, ""
    if "——" in quote:
        parts = [p.strip() for p in quote.split("——", 1)]
        quote_text = parts[0]
        quote_author = parts[1] if len(parts) > 1 else ""

    quote_text = safe_text(quote_text)
    quote_author = safe_text(quote_author)

    quote_html = (
        f"<blockquote><p>“{quote_text}” —— <strong>{quote_author}</strong></p></blockquote>"
        if quote_author
        else f"<blockquote><p>“{quote_text}”</p></blockquote>"
    )

    bullets = [safe_text(b) for b in (content.get("section4", {}).get("bullets", []) or [])]
    bullets_html = "".join(f"<li>{b}</li>" for b in bullets)

    h1 = safe_text(content.get("h1", "三月：日常与小确幸～"))
    h1_id = safe_id(h1)
    s1 = content.get("section1", {})
    s2 = content.get("section2", {})
    s3 = content.get("section3", {})
    s4 = content.get("section4", {})
    s5 = content.get("section5", {})
    s6 = content.get("section6", {})
    closing = safe_text(content.get("closing", ""))
    intro = safe_text(content.get("intro", ""))

    s1_title = safe_text(s1.get("title", "🌿 春天的信号"))
    s2_title = safe_text(s2.get("title", "🍲 厨房的小欢喜"))
    s3_title = safe_text(s3.get("title", "🚶 傍晚散步"))
    s4_title = safe_text(s4.get("title", "📝 小小计划"))
    s1_text = safe_text(s1.get("text", ""))
    s2_text = safe_text(s2.get("text", ""))
    s3_text = safe_text(s3.get("text", ""))
    s5_title = safe_text(s5.get("title", "✨ 小确幸清单"))
    s5_text = safe_text(s5.get("text", ""))
    s6_title = safe_text(s6.get("title", "🧺 生活碎片"))
    s6_text = safe_text(s6.get("text", ""))

    wall_html = build_photo_wall(img_rel_paths, captions)

    return (
        f'<article class="post-content" id="article-container">'
        f'<h1 id="{h1_id}"><a href="#{h1_id}" class="headerlink" title="{h1}"></a>{h1}</h1>'
        f"{quote_html}"
        f"<blockquote><p>{intro}</p></blockquote>"
        f'<h2 id="🌿-春天的信号"><a href="#🌿-春天的信号" class="headerlink" title="🌿 春天的信号"></a>{s1_title}</h2>'
        f'<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap">'
        f'<div style="flex:1;min-width:240px;"><p>{s1_text}</p></div>'
        f'<div style="flex:1;min-width:240px;"><figure><img src="{img_a}" alt="日常一角" style="width:100%;border-radius:8px;" />'
        f'<figcaption>{captions.get(Path(img_a).name, "日常一角")}</figcaption></figure></div>'
        f'</div>'
        f'<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin-top:10px;">'
        f'<div style="flex:1;min-width:240px;"><figure><img src="{img_b}" alt="当日心情" style="width:100%;border-radius:8px;" />'
        f'<figcaption>{captions.get(Path(img_b).name, "当日心情")}</figcaption></figure></div>'
        f'<div style="flex:1;min-width:240px;"><blockquote><p>这个月的每一次好心情，都是来自你的小小温柔。</p></blockquote></div>'
        f'</div>'
        f'<h3 id="🍲-厨房的小欢喜"><a href="#🍲-厨房的小欢喜" class="headerlink" title="🍲 厨房的小欢喜"></a>{s2_title}</h3>'
        f'<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap">'
        f'<div style="flex:1;min-width:240px;"><figure><img src="{img_c}" alt="这一餐" style="width:100%;border-radius:8px;" />'
        f'<figcaption>{captions.get(Path(img_c).name, "这一餐")}</figcaption></figure></div>'
        f'<div style="flex:1;min-width:240px;"><p>{s2_text}</p>'
        f'<figure><img src="{img_d}" alt="那一刻" style="width:100%;border-radius:8px;margin-top:8px;" />'
        f'<figcaption>{captions.get(Path(img_d).name, "那一刻")}</figcaption></figure></div>'
        f'</div>'
        f'<h3 id="🚶-傍晚散步"><a href="#🚶-傍晚散步" class="headerlink" title="🚶 傍晚散步"></a>{s3_title}</h3>'
        f'<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap">'
        f'<div style="flex:1;min-width:240px;"><p>{s3_text}</p></div>'
        f'<div style="flex:1;min-width:240px;"><figure><img src="{img_e}" alt="傍晚散步" style="width:100%;border-radius:8px;" />'
        f'<figcaption>{captions.get(Path(img_e).name, "傍晚的风，刚刚好。")}</figcaption></figure></div>'
        f'</div>'
        f'<h3 id="📝-小小计划"><a href="#📝-小小计划" class="headerlink" title="📝 小小计划"></a>{s4_title}</h3>'
        f"<ul>{bullets_html}</ul>"
        f'<h3 id="✨-小确幸清单"><a href="#✨-小确幸清单" class="headerlink" title="✨ 小确幸清单"></a>{s5_title}</h3>'
        f"<p>{s5_text}</p>"
        f'<h3 id="🧺-生活碎片"><a href="#🧺-生活碎片" class="headerlink" title="🧺 生活碎片"></a>{s6_title}</h3>'
        f"<p>{s6_text}</p>"
        '<h3 id="📸-回忆拼图"><a href="#📸-回忆拼图" class="headerlink" title="📸 回忆拼图"></a>📸 回忆拼图</h3>'
        f'{wall_html}'
        f'<hr><h2 id="🌟-结语"><a href="#🌟-结语" class="headerlink" title="🌟 结语"></a>🌟 结语</h2>'
        f"<p>{closing}</p>"
        f"<blockquote><p>愿我们在新的一个月里，仍被温柔和热爱拥抱。#月度日记 #日常记录</p></blockquote>"
        f"</article>"
    )


def update_counts_and_dates(html_text: str, total_posts: int, update_time: str, last_push_iso: str) -> str:
    html_text = re.sub(
        r'(<div class="headline">文章</div><div class="length-num">)(\d+)(</div>)',
        lambda m: f"{m.group(1)}{total_posts}{m.group(3)}",
        html_text,
    )
    html_text = re.sub(
        r'(<div class="item-name">文章数目 :</div><div class="item-count">)(\d+)(</div>)',
        lambda m: f"{m.group(1)}{total_posts}{m.group(3)}",
        html_text,
    )
    html_text = re.sub(
        r'(data-lastPushDate=")[^"]*(")',
        lambda m: f"{m.group(1)}{last_push_iso}{m.group(2)}",
        html_text,
    )
    html_text = re.sub(
        r"(postUpdate: ')([^']*)(')",
        lambda m: f"{m.group(1)}{update_time}{m.group(3)}",
        html_text,
    )
    return html_text


def repair_html_blocks(html_text: str, total_posts: int, last_push_iso: str) -> str:
    # Fix corrupted archives count link in sidebar site-data
    def fix_sidebar_archives(m: re.Match) -> str:
        inner = m.group(2)
        if 'class="headline">文章</div>' in inner:
            return m.group(0)
        correct_inner = f'<div class="headline">文章</div><div class="length-num">{total_posts}</div>'
        return f'{m.group(1)}{correct_inner}{m.group(3)}'

    html_text = re.sub(
        r'(sidebar-site-data site-data is-center"><a href="/Cola-Sprite.github.io/archives/">)(.*?)(</a>)',
        fix_sidebar_archives,
        html_text,
        flags=re.DOTALL,
    )

    # Fix corrupted webinfo count block like <div class="webinfo-item">\15\3</div>
    html_text = re.sub(
        r'<div class="webinfo-item">\\[^<]*</div>',
        f'<div class="webinfo-item"><div class="item-name">文章数目 :</div><div class="item-count">{total_posts}</div></div>',
        html_text,
    )

    # Fix last-push-date attribute corruption
    html_text = re.sub(
        r'<div class="item-count" id="last-push-date"[^>]*>',
        f'<div class="item-count" id="last-push-date" data-lastPushDate="{last_push_iso}">',
        html_text,
    )

    # Remove stray backref artifacts if any
    html_text = html_text.replace("\\g<1>", "").replace("\\1", "").replace("\\2", "").replace("\\3", "")

    return html_text


def update_post_page(
    template_text: str,
    new_title: str,
    desc: str,
    new_url: str,
    cover_rel: str,
    cover_abs: str,
    publish_iso: str,
    publish_title: str,
    publish_date: str,
    update_iso: str,
    update_title: str,
    update_date: str,
    update_time: str,
    article_html: str,
    prev_post_url: str,
    prev_post_title: str,
    prev_post_cover: str,
) -> str:
    text = template_text

    old_title = extract_first(r'<h1 class="post-title">([^<]+)</h1>', text)
    if old_title:
        text = text.replace(old_title, new_title)

    text = re.sub(
        r'(<title>)([^<]+)(</title>)',
        lambda m: f"{m.group(1)}{new_title} | 可乐&雪碧 日常{m.group(3)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta name="description" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{desc}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta property="og:description" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{desc}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta property="og:title" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{new_title}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta property="og:url" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{new_url}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(<link rel="canonical" href=")[^"]*(")',
        lambda m: f"{m.group(1)}{new_url}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta property="og:image" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{cover_abs}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(meta name="twitter:image" content=")[^"]*(")',
        lambda m: f"{m.group(1)}{cover_abs}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r'(data-image=")[^"]*(")',
        lambda m: f"{m.group(1)}{cover_abs}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r"(post-bg\"[^>]*background-image: url\(')([^']*)('\))",
        lambda m: f"{m.group(1)}{cover_rel}{m.group(3)}",
        text,
        count=1,
    )
    text = re.sub(
        r"(title: ')([^']*)(')",
        lambda m: f"{m.group(1)}{new_title}{m.group(3)}",
        text,
        count=1,
    )

    text = re.sub(
        r'(post-meta-date-created" datetime=")[^"]*(" title="发表于 )[^"]*(">)([^<]*)',
        lambda m: f"{m.group(1)}{publish_iso}{m.group(2)}{publish_title}{m.group(3)}{publish_date}",
        text,
        count=1,
    )
    text = re.sub(
        r'(post-meta-date-updated" datetime=")[^"]*(" title="更新于 )[^"]*(">)([^<]*)',
        lambda m: f"{m.group(1)}{update_iso}{m.group(2)}{update_title}{m.group(3)}{update_date}",
        text,
        count=1,
    )
    text = re.sub(
        r'(data-flag-title=")[^"]*(")',
        lambda m: f"{m.group(1)}{new_title}{m.group(2)}",
        text,
        count=1,
    )
    text = re.sub(
        r"(postUpdate: ')([^']*)(')",
        lambda m: f"{m.group(1)}{update_time}{m.group(3)}",
        text,
        count=1,
    )

    # Replace article content
    start = text.find('<article class="post-content" id="article-container">')
    end = text.find("</article>", start)
    if start != -1 and end != -1:
        end += len("</article>")
        text = text[:start] + article_html + text[end:]

    # Replace pagination (latest post -> only next)
    pagination = (
        '<nav class="pagination-post" id="pagination">'
        '<div class="next-post pull-full">'
        f'<a href="{prev_post_url}" title="{prev_post_title}">'
        f'<img class="cover" src="{prev_post_cover}" onerror="onerror=null;src=\'{SITE_ROOT}img/404.jpg\'" alt="cover of next post">'
        '<div class="pagination-info"><div class="label">下一篇</div>'
        f'<div class="next_info">{prev_post_title}</div></div></a></div></nav>'
    )
    pag_start = text.find('<nav class="pagination-post"')
    pag_end = text.find("</nav>", pag_start)
    if pag_start != -1 and pag_end != -1:
        pag_end += len("</nav>")
        text = text[:pag_start] + pagination + text[pag_end:]

    return text


def build_recent_post_item(
    link: str, title: str, cover: str, publish_iso: str, publish_title: str, publish_date: str, excerpt: str
) -> str:
    return (
        '<div class="recent-post-item">'
        '<div class="post_cover left">'
        f'<a href="{link}" title="{title}">'
        f'<img class="post-bg" src="{cover}" onerror="this.onerror=null;this.src=\'{SITE_ROOT}img/404.jpg\'" alt="{title}"></a>'
        "</div>"
        '<div class="recent-post-info">'
        f'<a class="article-title" href="{link}" title="{title}">{title}</a>'
        '<div class="article-meta-wrap"><span class="post-meta-date"><i class="far fa-calendar-alt"></i>'
        '<span class="article-meta-label">发表于</span>'
        f'<time datetime="{publish_iso}" title="{publish_title}">{publish_date}</time>'
        "</span></div>"
        f'<div class="content">{excerpt}</div>'
        "</div></div>"
    )


def build_recent_post_item_no_cover(
    link: str, title: str, publish_iso: str, publish_title: str, publish_date: str, excerpt: str
) -> str:
    return (
        '<div class="recent-post-item">'
        '<div class="recent-post-info no-cover">'
        f'<a class="article-title" href="{link}" title="{title}">{title}</a>'
        '<div class="article-meta-wrap"><span class="post-meta-date"><i class="far fa-calendar-alt"></i>'
        '<span class="article-meta-label">发表于</span>'
        f'<time datetime="{publish_iso}" title="{publish_title}">{publish_date}</time>'
        "</span></div>"
        f'<div class="content">{excerpt}</div>'
        "</div></div>"
    )


def collect_posts(max_posts: int = 6) -> List[Dict[str, str]]:
    posts = []
    for p in REPO_ROOT.rglob("index.html"):
        rel = p.relative_to(REPO_ROOT).as_posix()
        m = re.match(r"(\d{4})/(\d{2})/(\d{2})/([^/]+)/index.html$", rel)
        if not m:
            continue
        y, mo, d, _slug = m.groups()
        try:
            date_obj = dt.date(int(y), int(mo), int(d))
        except ValueError:
            continue
        if not is_valid_template(p):
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        title = extract_first(r'<h1 class="post-title">([^<]+)</h1>', text)
        if not title:
            title = extract_first(r"<title>([^<]+)</title>", text)
        title = title.replace(" | 可乐&雪碧 日常", "")
        publish_iso = extract_first(
            r'<time class="post-meta-date-created" datetime="([^"]+)"', text
        )
        if not publish_iso:
            publish_iso = date_obj.strftime("%Y-%m-%dT00:00:00.000Z")
        publish_date = extract_first(
            r'<time class="post-meta-date-created"[^>]*>([^<]+)</time>', text
        )
        if not publish_date:
            publish_date = date_obj.strftime("%Y-%m-%d")
        publish_title = extract_first(
            r'<time class="post-meta-date-created"[^>]*title="([^"]+)"', text
        )
        if not publish_title:
            publish_title = f"发表于 {publish_date} 08:00:00"
        cover = extract_first(r'meta property="og:image" content="([^"]+)"', text)
        excerpt = extract_first(r'meta name="description" content="([^"]*)"', text)
        if not excerpt:
            excerpt = extract_first(r"<h1[^>]*>([^<]+)</h1>", text)
        excerpt = safe_text(excerpt)
        excerpt = re.sub(r"\s+", " ", excerpt).strip()
        if len(excerpt) > 80:
            excerpt = excerpt[:80].rstrip() + "…"
        link = post_link_from_path(p)
        posts.append(
            {
                "date": date_obj.isoformat(),
                "link": link,
                "title": title,
                "cover": cover,
                "publish_iso": publish_iso,
                "publish_title": publish_title,
                "publish_date": publish_date,
                "excerpt": excerpt,
            }
        )
    posts.sort(key=lambda x: x["date"], reverse=True)
    return posts[:max_posts]


def rebuild_recent_posts_from_posts(html_text: str, max_posts: int = 6) -> str:
    anchor = '<div class="recent-posts" id="recent-posts">'
    anchor_idx = html_text.find(anchor)
    if anchor_idx == -1:
        return html_text
    nav_idx = html_text.find('<nav id="pagination"', anchor_idx)
    if nav_idx == -1:
        return html_text

    posts = collect_posts(max_posts=max_posts)
    if not posts:
        return html_text
    items = []
    for post in posts:
        if post["cover"]:
            items.append(
                build_recent_post_item(
                    link=post["link"],
                    title=post["title"],
                    cover=post["cover"],
                    publish_iso=post["publish_iso"],
                    publish_title=post["publish_title"],
                    publish_date=post["publish_date"],
                    excerpt=post["excerpt"],
                )
            )
        else:
            items.append(
                build_recent_post_item_no_cover(
                    link=post["link"],
                    title=post["title"],
                    publish_iso=post["publish_iso"],
                    publish_title=post["publish_title"],
                    publish_date=post["publish_date"],
                    excerpt=post["excerpt"],
                )
            )

    return html_text[: anchor_idx + len(anchor)] + "".join(items) + html_text[nav_idx:]


def build_archive_item(link: str, title: str, cover: str, publish_iso: str, publish_title: str, publish_date: str) -> str:
    return (
        '<div class="article-sort-item">'
        f'<a class="article-sort-item-img" href="{link}" title="{title}">'
        f'<img src="{cover}" alt="{title}" onerror="this.onerror=null;this.src=\'{SITE_ROOT}img/404.jpg\'"></a>'
        '<div class="article-sort-item-info"><div class="article-sort-item-time">'
        '<i class="far fa-calendar-alt"></i>'
        f'<time class="post-meta-date-created" datetime="{publish_iso}" title="{publish_title}">{publish_date}</time>'
        "</div>"
        f'<a class="article-sort-item-title" href="{link}" title="{title}">{title}</a>'
        "</div></div>"
    )


def update_archives_index(
    html_text: str,
    year: int,
    new_item: str,
) -> str:
    if 'href="' in new_item:
        link = extract_first(r'href="([^"]+)"', new_item)
        if link and link in html_text:
            return html_text
    year_marker = f'<div class="article-sort-item year">{year}</div>'
    if year_marker in html_text:
        return html_text.replace(year_marker, year_marker + new_item, 1)

    # Insert new year at the top of article-sort
    insert_point = '<div class="article-sort">'
    if insert_point in html_text:
        return html_text.replace(insert_point, insert_point + year_marker + new_item, 1)
    return html_text


def update_archive_list(html_text: str, month_link: str, month_label: str, count: int) -> str:
    if month_link in html_text:
        return html_text
    item = (
        '<li class="card-archive-list-item">'
        f'<a class="card-archive-list-link" href="{month_link}">'
        f'<span class="card-archive-list-date">{month_label}</span>'
        f'<span class="card-archive-list-count">{count}</span>'
        "</a></li>"
    )
    anchor = '<ul class="card-archive-list">'
    if anchor in html_text:
        return html_text.replace(anchor, anchor + item, 1)
    return html_text


def update_search_xml(search_text: str, title: str, link: str, url: str, article_html: str) -> str:
    if f"<url>{url}</url>" in search_text:
        return search_text
    entry = (
        "\n    <entry>\n"
        f"      <title>{title}</title>\n"
        f"      <link href=\"{link}\"/>\n"
        f"      <url>{url}</url>\n"
        "      \n"
        "        <content type=\"html\"><![CDATA["
        "<link rel=\"stylesheet\" class=\"aplayer-secondary-style-marker\" href=\"/Cola-Sprite.github.io/assets/css/APlayer.min.css\">"
        "<script src=\"/Cola-Sprite.github.io/assets/js/APlayer.min.js\" class=\"aplayer-secondary-script-marker\"></script>"
        f"{article_html}]]></content>\n"
        "      \n"
        "      \n"
        "      \n"
        "    </entry>\n"
    )
    insert_point = "<search>"
    idx = search_text.find(insert_point)
    if idx == -1:
        return search_text
    insert_at = idx + len(insert_point)
    return search_text[:insert_at] + entry + search_text[insert_at:]


def main() -> int:
    args = parse_args()

    year, month = parse_month(args.month)
    publish_date = parse_date(args.date)
    month_str = f"{month:02d}"
    month_cn = CN_MONTHS[month - 1]

    src_dir = SOURCE_BASE / f"{year}-{month_str}"
    if args.photos:
        print("Exporting random photos from Photos.app...")
        ok = export_random_photos_from_photos(
            year=year,
            month=month,
            dest_dir=src_dir,
            count=args.photos_count,
            library_path=args.photos_library,
        )
        if not ok:
            return 1
    images = list_images(src_dir)
    if not images:
        print(f"ERROR: No images found in {src_dir}")
        return 1

    cover = pick_cover(images)
    if cover is None:
        print("ERROR: Could not pick a cover image.")
        return 1

    ensure_copy_images(images, REPO_ROOT / "img" / f"{year}-{month_str}", args.dry_run)

    title = f"{year}年{month_str} Daily！"
    desc_default = f"{month_cn}：日常与小确幸～"

    # Analyze images first to get descriptions
    image_descriptions = ""
    if not args.no_openclaw:
        print("Analyzing images with vision model...")
        image_descriptions = analyze_images(images, args.openclaw_path)
        if image_descriptions:
            print(f"Got image descriptions for {len(images[:4])} images")
    
    prompt = build_prompt(year, month_cn, title, [p.name for p in images], image_descriptions)
    content = None if args.no_openclaw else openclaw_generate(prompt, args.openclaw_path)
    if not content:
        content = fallback_content(year, month_cn)

    # Build article
    captions = build_image_captions(images)
    img_rel_paths = [
        f"{SITE_ROOT}img/{year}-{month_str}/{p.name}"
        for p in images
        if p.name != cover.name
    ]
    if not img_rel_paths:
        img_rel_paths = [f"{SITE_ROOT}img/{year}-{month_str}/{cover.name}"]

    article_html = build_article_html(content, img_rel_paths, captions)

    # New post path
    slug = f"{year}{month_str}"
    post_dir = REPO_ROOT / str(year) / month_str / f"{publish_date.day:02d}" / slug
    post_path = post_dir / "index.html"
    if post_path.exists():
        if not args.overwrite:
            print(f"ERROR: Post already exists: {post_path}")
            return 1
        else:
            print(f"Overwriting existing post: {post_path}")

    template_path = find_latest_post()
    template_text = template_path.read_text(encoding="utf-8")

    cover_rel = f"{SITE_ROOT}img/{year}-{month_str}/{cover.name}"
    cover_abs = f"https://jiujiu991.github.io{cover_rel}"
    post_url = f"https://jiujiu991.github.io{SITE_ROOT}{year}/{month_str}/{publish_date.day:02d}/{slug}/index.html"
    post_link = f"{SITE_ROOT}{year}/{month_str}/{publish_date.day:02d}/{slug}/"

    publish_iso = f"{publish_date.isoformat()}T00:00:00.000Z"
    update_iso = f"{publish_date.isoformat()}T12:00:00.000Z"
    publish_title = f"发表于 {publish_date} 08:00:00"
    update_title = f"更新于 {publish_date} 20:00:00"
    publish_date_str = publish_date.isoformat()
    update_date_str = publish_date.isoformat()
    update_time = f"{publish_date} 20:00:00"
    last_push_iso = f"{publish_date.isoformat()}T12:00:00.000Z"

    prev_title = extract_first(r'<h1 class="post-title">([^<]+)</h1>', template_text, "上一篇")
    prev_url = extract_first(r'<link rel="canonical" href="([^"]+)"', template_text, "")
    prev_link = prev_url.replace("https://jiujiu991.github.io", "") if prev_url else post_link_from_path(template_path)
    prev_cover = extract_first(r'meta property="og:image" content="([^"]+)"', template_text, cover_abs)

    updated_post = update_post_page(
        template_text=template_text,
        new_title=title,
        desc=content.get("h1", desc_default),
        new_url=post_url,
        cover_rel=cover_rel,
        cover_abs=cover_abs,
        publish_iso=publish_iso,
        publish_title=publish_title,
        publish_date=publish_date_str,
        update_iso=update_iso,
        update_title=update_title,
        update_date=update_date_str,
        update_time=update_time,
        article_html=article_html,
        prev_post_url=prev_link,
        prev_post_title=prev_title,
        prev_post_cover=prev_cover,
    )

    if not args.dry_run:
        post_dir.mkdir(parents=True, exist_ok=True)
        post_path.write_text(updated_post, encoding="utf-8")

    # Update index.html
    index_path = REPO_ROOT / "index.html"
    if index_path.exists():
        index_text = index_path.read_text(encoding="utf-8")
        new_item = build_recent_post_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
            excerpt=content.get("h1", desc_default),
        )
        anchor = '<div class="recent-posts" id="recent-posts">'
        if anchor in index_text and post_link not in index_text:
            index_text = index_text.replace(anchor, anchor + new_item, 1)
        index_text = rebuild_recent_posts_from_posts(index_text, max_posts=6)
        index_path.write_text(index_text, encoding="utf-8")

    # Update archives index
    archives_index = REPO_ROOT / "archives" / "index.html"
    if archives_index.exists():
        arch_text = archives_index.read_text(encoding="utf-8")
        arch_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        arch_text = update_archives_index(arch_text, year, arch_item)
        arch_text = update_archive_list(
            arch_text,
            month_link=f"{SITE_ROOT}archives/{year}/{month_str}/",
            month_label=f"{month_cn} {year}",
            count=1,
        )
        archives_index.write_text(arch_text, encoding="utf-8")

    # Create/update monthly archive page
    month_archive_path = REPO_ROOT / "archives" / str(year) / month_str / "index.html"
    if month_archive_path.exists():
        month_text = month_archive_path.read_text(encoding="utf-8")
        month_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        month_text = update_archives_index(month_text, year, month_item)
        month_text = re.sub(
            r'(文章总览 - )\d+',
            lambda m: f"{m.group(1)}1",
            month_text,
        )
        month_archive_path.write_text(month_text, encoding="utf-8")
    else:
        # Use any existing archive month as template
        template_arch = next(REPO_ROOT.glob("archives/*/*/index.html"))
        month_text = template_arch.read_text(encoding="utf-8")
        month_text = month_text.replace(
            extract_first(r"<title>([^<]+)</title>", month_text, ""),
            f"{month_cn} {year} | 可乐&雪碧 日常",
        )
        month_text = month_text.replace(
            extract_first(r'meta property="og:title" content="([^"]+)"', month_text, ""),
            f"{month_cn} {year}",
        )
        month_text = month_text.replace(
            extract_first(r'meta property="og:url" content="([^"]+)"', month_text, ""),
            f"https://jiujiu991.github.io{SITE_ROOT}archives/{year}/{month_str}/index.html",
        )
        month_text = month_text.replace(
            extract_first(r'<link rel="canonical" href="([^"]+)"', month_text, ""),
            f"https://jiujiu991.github.io{SITE_ROOT}archives/{year}/{month_str}/index.html",
        )
        month_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        month_block = f'<div class="article-sort"><div class="article-sort-item year">{year}</div>{month_item}</div>'
        month_text = re.sub(r'<div class="article-sort">.*?</nav>', month_block + '<nav', month_text, flags=re.DOTALL)
        month_text = re.sub(
            r'(文章总览 - )\d+',
            lambda m: f"{m.group(1)}1",
            month_text,
        )
        if not args.dry_run:
            month_archive_path.parent.mkdir(parents=True, exist_ok=True)
            month_archive_path.write_text(month_text, encoding="utf-8")

    # Update search.xml
    search_path = REPO_ROOT / "search.xml"
    if search_path.exists():
        search_text = search_path.read_text(encoding="utf-8")
        search_text = update_search_xml(search_text, title, post_link, post_link, article_html)
        search_path.write_text(search_text, encoding="utf-8")

    # Update counts + timestamps across key pages
    if search_path.exists():
        total_posts = search_path.read_text(encoding="utf-8").count("<entry>")
    else:
        total_posts = 0

    # Update counts + timestamps across all html pages
    for p in REPO_ROOT.rglob("*.html"):
        html = p.read_text(encoding="utf-8")
        html = repair_html_blocks(html, total_posts, last_push_iso)
        html = update_counts_and_dates(html, total_posts, update_time, last_push_iso)
        # Ensure archive list has the current month
        html = update_archive_list(
            html,
            month_link=f"{SITE_ROOT}archives/{year}/{month_str}/",
            month_label=f"{month_cn} {year}",
            count=1,
        )
        # Update per-page archive count if present
        if "文章总览 -" in html:
            page_count = html.count('class="article-sort-item-img"')
            html = re.sub(
                r'(文章总览 - )\d+',
                lambda m: f"{m.group(1)}{page_count}",
                html,
            )
        p.write_text(html, encoding="utf-8")

    print(f"OK: Generated {post_path}")
    print(f"Cover: {cover_rel}")
    if args.push and not args.dry_run:
        commit_msg = args.commit_message or f"Add {title}"
        git_add_paths = [
            str(post_path.relative_to(REPO_ROOT)),
            str(index_path.relative_to(REPO_ROOT)),
            str(archives_index.relative_to(REPO_ROOT)),
            str(month_archive_path.relative_to(REPO_ROOT)),
            f"img/{year}-{month_str}",
        ]
        subprocess.run(["git", "add", "--"] + git_add_paths, cwd=str(REPO_ROOT), check=False)
        subprocess.run(["git", "commit", "-m", commit_msg], cwd=str(REPO_ROOT), check=False)
        subprocess.run(["git", "push"], cwd=str(REPO_ROOT), check=False)
        print("Git push: done.")
    else:
        print("Next steps:")
        print(f"  git add -A && git commit -m \"Add {title}\" && git push")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
