#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-publish a monthly "Daily" post for this static site.

Defaults:
- Source images: /Users/chengqian/Documents/colo/img/YYYY-MM/
- Publish month: previous month (so running on the 1st summarizes last month)
- Publish date: today
- Cover: cover.* if present, else most recently modified image
- Text: generated by OpenClaw local agent (openclaw agent --local)

Usage:
  python3 scripts/publish_month.py
  python3 scripts/publish_month.py --month 2025-03 --date 2025-04-01
  python3 scripts/publish_month.py --no-openclaw
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_ROOT = "/Cola-Sprite.github.io/"
SOURCE_BASE = Path("/Users/chengqian/Documents/colo/img")
OPENCLAW = Path("/opt/homebrew/bin/openclaw")

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}

CN_MONTHS = [
    "一月", "二月", "三月", "四月", "五月", "六月",
    "七月", "八月", "九月", "十月", "十一月", "十二月",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--month", help="Target month in YYYY-MM (default: previous month).")
    parser.add_argument("--date", help="Publish date YYYY-MM-DD (default: today).")
    parser.add_argument("--no-openclaw", action="store_true", help="Skip OpenClaw and use fallback text.")
    parser.add_argument("--openclaw-path", default=str(OPENCLAW), help="Path to openclaw binary.")
    parser.add_argument("--push", action="store_true", help="Auto git add/commit/push.")
    parser.add_argument("--commit-message", default="", help="Custom git commit message.")
    parser.add_argument("--dry-run", action="store_true", help="Do not write files.")
    return parser.parse_args()


def month_previous(today: dt.date) -> Tuple[int, int]:
    first = today.replace(day=1)
    prev_last = first - dt.timedelta(days=1)
    return prev_last.year, prev_last.month


def parse_month(month_str: Optional[str]) -> Tuple[int, int]:
    if not month_str:
        return month_previous(dt.date.today())
    m = re.fullmatch(r"(\d{4})-(\d{2})", month_str)
    if not m:
        raise ValueError("Month must be in YYYY-MM format.")
    return int(m.group(1)), int(m.group(2))


def parse_date(date_str: Optional[str]) -> dt.date:
    if not date_str:
        return dt.date.today()
    return dt.datetime.strptime(date_str, "%Y-%m-%d").date()


def list_images(src_dir: Path) -> List[Path]:
    if not src_dir.exists():
        return []
    images = []
    for p in src_dir.iterdir():
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS:
            images.append(p)
    return sorted(images)


def pick_cover(images: List[Path]) -> Optional[Path]:
    if not images:
        return None
    cover = [p for p in images if p.stem.lower().startswith("cover")]
    if cover:
        return sorted(cover)[0]
    return max(images, key=lambda p: p.stat().st_mtime)


def ensure_copy_images(images: List[Path], dst_dir: Path, dry_run: bool) -> None:
    if dry_run:
        return
    dst_dir.mkdir(parents=True, exist_ok=True)
    for img in images:
        shutil.copy2(img, dst_dir / img.name)
        os.chmod(dst_dir / img.name, 0o644)


def find_latest_post() -> Path:
    posts = []
    for p in REPO_ROOT.rglob("index.html"):
        rel = p.relative_to(REPO_ROOT).as_posix()
        m = re.match(r"(\d{4})/(\d{2})/(\d{2})/[^/]+/index.html$", rel)
        if not m:
            continue
        y, mo, d = map(int, m.groups())
        posts.append((dt.date(y, mo, d), p))
    if not posts:
        raise RuntimeError("No existing posts found to use as template.")
    posts.sort(key=lambda x: x[0], reverse=True)
    return posts[0][1]


def post_link_from_path(path: Path) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    m = re.match(r"(\d{4})/(\d{2})/(\d{2})/([^/]+)/index.html$", rel)
    if not m:
        return ""
    y, mo, d, slug = m.groups()
    return f"{SITE_ROOT}{y}/{mo}/{d}/{slug}/"


def extract_first(pattern: str, text: str, default: str = "") -> str:
    m = re.search(pattern, text, re.DOTALL)
    return m.group(1) if m else default


def openclaw_generate(prompt: str, openclaw_path: str) -> Optional[Dict]:
    if not Path(openclaw_path).exists():
        return None
    try:
        result = subprocess.run(
            [openclaw_path, "agent", "--local", "--message", prompt],
            check=False,
            capture_output=True,
            text=True,
            timeout=600,
        )
    except Exception:
        return None

    output = (result.stdout or "").strip()
    if not output:
        return None

    # Try to extract JSON from output
    start = output.find("{")
    end = output.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(output[start : end + 1])
    except Exception:
        return None


def fallback_content(year: int, month_cn: str) -> Dict:
    return {
        "h1": f"{month_cn}：日常与小确幸～",
        "quote": "“日子缓缓，温柔自来。” —— 佚名",
        "intro": f"{year}年的{month_cn}，我们把节奏放慢了一点，把心放稳了一点。",
        "section1": {
            "title": "🌿 春天的信号",
            "text": "天气逐渐转暖，风也变得柔和。我们在忙碌里留出一点小空隙，去感受生活的细微变化。",
        },
        "section2": {
            "title": "🍲 厨房的小欢喜",
            "text": "一顿简单的家常饭，也能让一天变得很踏实。热气升起的时候，心也跟着安静下来。",
        },
        "section3": {
            "title": "🚶 傍晚散步",
            "text": "下班后的路，走得不快，却很安心。我们聊着琐事，也聊着新的小目标。",
        },
        "section4": {
            "title": "📝 小小计划",
            "bullets": [
                "每周固定两次运动，保持轻松但稳定。",
                "尽量早睡早起，给身体一点缓冲。",
                "把每个月的日常继续记录下来。",
            ],
        },
        "closing": "愿我们在新的一个月里，依旧被温柔和热爱包围。",
    }


def build_prompt(year: int, month_cn: str, title: str, image_names: List[str]) -> str:
    image_list = "\n".join(f"- {name}" for name in image_names[:8])
    return (
        "你是写作爱人日常的中文博客作者。请写一篇温暖、细腻、生活化的月度记录。\n"
        f"标题主题：{title}\n"
        f"月份：{year}年{month_cn}\n"
        "可参考的图片文件名（仅用于灵感，不要逐一描述）：\n"
        f"{image_list}\n"
        "\n"
        "请严格输出 JSON，不要包含其它文字。JSON 格式如下：\n"
        "{\n"
        '  \"h1\": \"三月：xxxx～\",\n'
        '  \"quote\": \"一句话 —— 作者\",\n'
        '  \"intro\": \"2-3 句话的引入\",\n'
        '  \"section1\": {\"title\": \"🌿 春天的信号\", \"text\": \"...\"},\n'
        '  \"section2\": {\"title\": \"🍲 厨房的小欢喜\", \"text\": \"...\"},\n'
        '  \"section3\": {\"title\": \"🚶 傍晚散步\", \"text\": \"...\"},\n'
        '  \"section4\": {\"title\": \"📝 小小计划\", \"bullets\": [\"...\", \"...\", \"...\"]},\n'
        '  \"closing\": \"结语 1-2 句\"\n'
        "}\n"
        "要求：语言自然、温柔，不要提到AI或提示词。"
    )


def build_article_html(content: Dict, img_rel_paths: List[str]) -> str:
    # Ensure we have at least 4 images to place
    imgs = (img_rel_paths + img_rel_paths[:4])[:4]
    img_a, img_b, img_c, img_d = imgs

    quote = content.get("quote", "")
    quote_text, quote_author = quote, ""
    if "——" in quote:
        parts = [p.strip() for p in quote.split("——", 1)]
        quote_text = parts[0]
        quote_author = parts[1] if len(parts) > 1 else ""

    quote_html = (
        f"<blockquote><p>“{quote_text}” —— <strong>{quote_author}</strong></p></blockquote>"
        if quote_author
        else f"<blockquote><p>“{quote_text}”</p></blockquote>"
    )

    bullets = content.get("section4", {}).get("bullets", []) or []
    bullets_html = "".join(f"<li>{b}</li>" for b in bullets)

    h1 = content.get("h1", "三月：日常与小确幸～")
    s1 = content.get("section1", {})
    s2 = content.get("section2", {})
    s3 = content.get("section3", {})
    s4 = content.get("section4", {})
    closing = content.get("closing", "")
    intro = content.get("intro", "")

    return (
        f'<article class="post-content" id="article-container">'
        f'<h1 id="{h1}"><a href="#{h1}" class="headerlink" title="{h1}"></a>{h1}</h1>'
        f"{quote_html}"
        f"<blockquote><p>{intro}</p></blockquote>"
        f'<h2 id="🌿-春天的信号"><a href="#🌿-春天的信号" class="headerlink" title="🌿 春天的信号"></a>{s1.get("title", "🌿 春天的信号")}</h2>'
        f"<p>{s1.get('text','')}</p>"
        '<table><thead><tr><th>日常一角</th><th>当日心情</th></tr></thead>'
        f'<tbody><tr><td><img src="{img_a}" alt="日常一角" style="zoom:40%;" /></td>'
        f'<td><img src="{img_b}" alt="当日心情" style="zoom:40%;" /></td></tr></tbody></table>'
        f'<h3 id="🍲-厨房的小欢喜"><a href="#🍲-厨房的小欢喜" class="headerlink" title="🍲 厨房的小欢喜"></a>{s2.get("title","🍲 厨房的小欢喜")}</h3>'
        f"<p>{s2.get('text','')}</p>"
        f'<p><img src="{img_c}" alt="厨房小欢喜" style="zoom:60%;" /></p>'
        f'<h3 id="🚶-傍晚散步"><a href="#🚶-傍晚散步" class="headerlink" title="🚶 傍晚散步"></a>{s3.get("title","🚶 傍晚散步")}</h3>'
        f"<p>{s3.get('text','')}</p>"
        f'<p><img src="{img_d}" alt="傍晚散步" style="zoom:60%;" /></p>'
        f'<h3 id="📝-小小计划"><a href="#📝-小小计划" class="headerlink" title="📝 小小计划"></a>{s4.get("title","📝 小小计划")}</h3>'
        f"<ul>{bullets_html}</ul>"
        f'<hr><h2 id="🌟-结语"><a href="#🌟-结语" class="headerlink" title="🌟 结语"></a>🌟 结语</h2>'
        f"<p>{closing}</p>"
        f"<blockquote><p>愿我们在新的一个月里，仍被温柔和热爱拥抱。#月度日记 #日常记录</p></blockquote>"
        f"</article>"
    )


def update_counts_and_dates(html_text: str, total_posts: int, update_time: str, last_push_iso: str) -> str:
    html_text = re.sub(
        r'(<div class="headline">文章</div><div class="length-num">)(\d+)(</div>)',
        rf"\\1{total_posts}\\3",
        html_text,
    )
    html_text = re.sub(
        r'(<div class="item-name">文章数目 :</div><div class="item-count">)(\d+)(</div>)',
        rf"\\1{total_posts}\\3",
        html_text,
    )
    html_text = re.sub(
        r'(data-lastPushDate=")[^"]*(")',
        rf"\\1{last_push_iso}\\2",
        html_text,
    )
    html_text = re.sub(
        r"(postUpdate: ')([^']*)(')",
        rf"\\1{update_time}\\3",
        html_text,
    )
    return html_text


def update_post_page(
    template_text: str,
    new_title: str,
    desc: str,
    new_url: str,
    cover_rel: str,
    cover_abs: str,
    publish_iso: str,
    publish_title: str,
    publish_date: str,
    update_iso: str,
    update_title: str,
    update_date: str,
    update_time: str,
    article_html: str,
    prev_post_url: str,
    prev_post_title: str,
    prev_post_cover: str,
) -> str:
    text = template_text

    old_title = extract_first(r'<h1 class="post-title">([^<]+)</h1>', text)
    if old_title:
        text = text.replace(old_title, new_title)

    text = re.sub(
        r'(<title>)([^<]+)(</title>)',
        rf"\\1{new_title} | 可乐&雪碧 日常\\3",
        text,
        count=1,
    )
    text = re.sub(r'(meta name="description" content=")[^"]*(")', rf"\\1{desc}\\2", text, count=1)
    text = re.sub(r'(meta property="og:description" content=")[^"]*(")', rf"\\1{desc}\\2", text, count=1)
    text = re.sub(r'(meta property="og:title" content=")[^"]*(")', rf"\\1{new_title}\\2", text, count=1)
    text = re.sub(r'(meta property="og:url" content=")[^"]*(")', rf"\\1{new_url}\\2", text, count=1)
    text = re.sub(r'(<link rel="canonical" href=")[^"]*(")', rf"\\1{new_url}\\2", text, count=1)
    text = re.sub(r'(meta property="og:image" content=")[^"]*(")', rf"\\1{cover_abs}\\2", text, count=1)
    text = re.sub(r'(meta name="twitter:image" content=")[^"]*(")', rf"\\1{cover_abs}\\2", text, count=1)
    text = re.sub(r'(data-image=")[^"]*(")', rf"\\1{cover_abs}\\2", text, count=1)
    text = re.sub(
        r"(post-bg\"[^>]*background-image: url\(')([^']*)('\))",
        rf"\\1{cover_rel}\\3",
        text,
        count=1,
    )
    text = re.sub(r"(title: ')([^']*)(')", rf"\\1{new_title}\\3", text, count=1)

    text = re.sub(
        r'(post-meta-date-created" datetime=")[^"]*(" title="发表于 )[^"]*(">)([^<]*)',
        rf"\\1{publish_iso}\\2{publish_title}\\3{publish_date}",
        text,
        count=1,
    )
    text = re.sub(
        r'(post-meta-date-updated" datetime=")[^"]*(" title="更新于 )[^"]*(">)([^<]*)',
        rf"\\1{update_iso}\\2{update_title}\\3{update_date}",
        text,
        count=1,
    )
    text = re.sub(r'(data-flag-title=")[^"]*(")', rf"\\1{new_title}\\2", text, count=1)
    text = re.sub(r"(postUpdate: ')([^']*)(')", rf"\\1{update_time}\\3", text, count=1)

    # Replace article content
    start = text.find('<article class="post-content" id="article-container">')
    end = text.find("</article>", start)
    if start != -1 and end != -1:
        end += len("</article>")
        text = text[:start] + article_html + text[end:]

    # Replace pagination (latest post -> only next)
    pagination = (
        '<nav class="pagination-post" id="pagination">'
        '<div class="next-post pull-full">'
        f'<a href="{prev_post_url}" title="{prev_post_title}">'
        f'<img class="cover" src="{prev_post_cover}" onerror="onerror=null;src=\'{SITE_ROOT}img/404.jpg\'" alt="cover of next post">'
        '<div class="pagination-info"><div class="label">下一篇</div>'
        f'<div class="next_info">{prev_post_title}</div></div></a></div></nav>'
    )
    pag_start = text.find('<nav class="pagination-post"')
    pag_end = text.find("</nav>", pag_start)
    if pag_start != -1 and pag_end != -1:
        pag_end += len("</nav>")
        text = text[:pag_start] + pagination + text[pag_end:]

    return text


def build_recent_post_item(
    link: str, title: str, cover: str, publish_iso: str, publish_title: str, publish_date: str, excerpt: str
) -> str:
    return (
        '<div class="recent-post-item">'
        '<div class="post_cover left">'
        f'<a href="{link}" title="{title}">'
        f'<img class="post-bg" src="{cover}" onerror="this.onerror=null;this.src=\'{SITE_ROOT}img/404.jpg\'" alt="{title}"></a>'
        "</div>"
        '<div class="recent-post-info">'
        f'<a class="article-title" href="{link}" title="{title}">{title}</a>'
        '<div class="article-meta-wrap"><span class="post-meta-date"><i class="far fa-calendar-alt"></i>'
        '<span class="article-meta-label">发表于</span>'
        f'<time datetime="{publish_iso}" title="{publish_title}">{publish_date}</time>'
        "</span></div>"
        f'<div class="content">{excerpt}</div>'
        "</div></div>"
    )


def build_archive_item(link: str, title: str, cover: str, publish_iso: str, publish_title: str, publish_date: str) -> str:
    return (
        '<div class="article-sort-item">'
        f'<a class="article-sort-item-img" href="{link}" title="{title}">'
        f'<img src="{cover}" alt="{title}" onerror="this.onerror=null;this.src=\'{SITE_ROOT}img/404.jpg\'"></a>'
        '<div class="article-sort-item-info"><div class="article-sort-item-time">'
        '<i class="far fa-calendar-alt"></i>'
        f'<time class="post-meta-date-created" datetime="{publish_iso}" title="{publish_title}">{publish_date}</time>'
        "</div>"
        f'<a class="article-sort-item-title" href="{link}" title="{title}">{title}</a>'
        "</div></div>"
    )


def update_archives_index(
    html_text: str,
    year: int,
    new_item: str,
) -> str:
    year_marker = f'<div class="article-sort-item year">{year}</div>'
    if year_marker in html_text:
        return html_text.replace(year_marker, year_marker + new_item, 1)

    # Insert new year at the top of article-sort
    insert_point = '<div class="article-sort">'
    if insert_point in html_text:
        return html_text.replace(insert_point, insert_point + year_marker + new_item, 1)
    return html_text


def update_archive_list(html_text: str, month_link: str, month_label: str, count: int) -> str:
    if month_link in html_text:
        return html_text
    item = (
        '<li class="card-archive-list-item">'
        f'<a class="card-archive-list-link" href="{month_link}">'
        f'<span class="card-archive-list-date">{month_label}</span>'
        f'<span class="card-archive-list-count">{count}</span>'
        "</a></li>"
    )
    anchor = '<ul class="card-archive-list">'
    if anchor in html_text:
        return html_text.replace(anchor, anchor + item, 1)
    return html_text


def update_search_xml(search_text: str, title: str, link: str, url: str, article_html: str) -> str:
    if f"<url>{url}</url>" in search_text:
        return search_text
    entry = (
        "\n    <entry>\n"
        f"      <title>{title}</title>\n"
        f"      <link href=\"{link}\"/>\n"
        f"      <url>{url}</url>\n"
        "      \n"
        "        <content type=\"html\"><![CDATA["
        "<link rel=\"stylesheet\" class=\"aplayer-secondary-style-marker\" href=\"/Cola-Sprite.github.io/assets/css/APlayer.min.css\">"
        "<script src=\"/Cola-Sprite.github.io/assets/js/APlayer.min.js\" class=\"aplayer-secondary-script-marker\"></script>"
        f"{article_html}]]></content>\n"
        "      \n"
        "      \n"
        "      \n"
        "    </entry>\n"
    )
    insert_point = "<search>"
    idx = search_text.find(insert_point)
    if idx == -1:
        return search_text
    insert_at = idx + len(insert_point)
    return search_text[:insert_at] + entry + search_text[insert_at:]


def main() -> int:
    args = parse_args()

    year, month = parse_month(args.month)
    publish_date = parse_date(args.date)
    month_str = f"{month:02d}"
    month_cn = CN_MONTHS[month - 1]

    src_dir = SOURCE_BASE / f"{year}-{month_str}"
    images = list_images(src_dir)
    if not images:
        print(f"ERROR: No images found in {src_dir}")
        return 1

    cover = pick_cover(images)
    if cover is None:
        print("ERROR: Could not pick a cover image.")
        return 1

    ensure_copy_images(images, REPO_ROOT / "img" / f"{year}-{month_str}", args.dry_run)

    title = f"{year}年{month_str} Daily！"
    desc_default = f"{month_cn}：日常与小确幸～"

    prompt = build_prompt(year, month_cn, title, [p.name for p in images])
    content = None if args.no_openclaw else openclaw_generate(prompt, args.openclaw_path)
    if not content:
        content = fallback_content(year, month_cn)

    # Build article
    img_rel_paths = [
        f"{SITE_ROOT}img/{year}-{month_str}/{p.name}"
        for p in images
        if p.name != cover.name
    ]
    if not img_rel_paths:
        img_rel_paths = [f"{SITE_ROOT}img/{year}-{month_str}/{cover.name}"]

    article_html = build_article_html(content, img_rel_paths)

    # New post path
    slug = f"{year}{month_str}"
    post_dir = REPO_ROOT / str(year) / month_str / f"{publish_date.day:02d}" / slug
    post_path = post_dir / "index.html"
    if post_path.exists():
        print(f"ERROR: Post already exists: {post_path}")
        return 1

    template_path = find_latest_post()
    template_text = template_path.read_text(encoding="utf-8")

    cover_rel = f"{SITE_ROOT}img/{year}-{month_str}/{cover.name}"
    cover_abs = f"https://jiujiu991.github.io{cover_rel}"
    post_url = f"https://jiujiu991.github.io{SITE_ROOT}{year}/{month_str}/{publish_date.day:02d}/{slug}/index.html"
    post_link = f"{SITE_ROOT}{year}/{month_str}/{publish_date.day:02d}/{slug}/"

    publish_iso = f"{publish_date.isoformat()}T00:00:00.000Z"
    update_iso = f"{publish_date.isoformat()}T12:00:00.000Z"
    publish_title = f"发表于 {publish_date} 08:00:00"
    update_title = f"更新于 {publish_date} 20:00:00"
    publish_date_str = publish_date.isoformat()
    update_date_str = publish_date.isoformat()
    update_time = f"{publish_date} 20:00:00"
    last_push_iso = f"{publish_date.isoformat()}T12:00:00.000Z"

    prev_title = extract_first(r'<h1 class="post-title">([^<]+)</h1>', template_text, "上一篇")
    prev_url = extract_first(r'<link rel="canonical" href="([^"]+)"', template_text, "")
    prev_link = prev_url.replace("https://jiujiu991.github.io", "") if prev_url else post_link_from_path(template_path)
    prev_cover = extract_first(r'meta property="og:image" content="([^"]+)"', template_text, cover_abs)

    updated_post = update_post_page(
        template_text=template_text,
        new_title=title,
        desc=content.get("h1", desc_default),
        new_url=post_url,
        cover_rel=cover_rel,
        cover_abs=cover_abs,
        publish_iso=publish_iso,
        publish_title=publish_title,
        publish_date=publish_date_str,
        update_iso=update_iso,
        update_title=update_title,
        update_date=update_date_str,
        update_time=update_time,
        article_html=article_html,
        prev_post_url=prev_link,
        prev_post_title=prev_title,
        prev_post_cover=prev_cover,
    )

    if not args.dry_run:
        post_dir.mkdir(parents=True, exist_ok=True)
        post_path.write_text(updated_post, encoding="utf-8")

    # Update index.html
    index_path = REPO_ROOT / "index.html"
    if index_path.exists():
        index_text = index_path.read_text(encoding="utf-8")
        new_item = build_recent_post_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
            excerpt=content.get("h1", desc_default),
        )
        anchor = '<div class="recent-posts" id="recent-posts">'
        if anchor in index_text:
            index_text = index_text.replace(anchor, anchor + new_item, 1)
        index_path.write_text(index_text, encoding="utf-8")

    # Update archives index
    archives_index = REPO_ROOT / "archives" / "index.html"
    if archives_index.exists():
        arch_text = archives_index.read_text(encoding="utf-8")
        arch_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        arch_text = update_archives_index(arch_text, year, arch_item)
        arch_text = update_archive_list(
            arch_text,
            month_link=f"{SITE_ROOT}archives/{year}/{month_str}/",
            month_label=f"{month_cn} {year}",
            count=1,
        )
        archives_index.write_text(arch_text, encoding="utf-8")

    # Create/update monthly archive page
    month_archive_path = REPO_ROOT / "archives" / str(year) / month_str / "index.html"
    if month_archive_path.exists():
        month_text = month_archive_path.read_text(encoding="utf-8")
        month_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        month_text = update_archives_index(month_text, year, month_item)
        month_text = re.sub(r'(文章总览 - )\d+', r"\\g<1>1", month_text)
        month_archive_path.write_text(month_text, encoding="utf-8")
    else:
        # Use any existing archive month as template
        template_arch = next(REPO_ROOT.glob("archives/*/*/index.html"))
        month_text = template_arch.read_text(encoding="utf-8")
        month_text = month_text.replace(
            extract_first(r"<title>([^<]+)</title>", month_text, ""),
            f"{month_cn} {year} | 可乐&雪碧 日常",
        )
        month_text = month_text.replace(
            extract_first(r'meta property="og:title" content="([^"]+)"', month_text, ""),
            f"{month_cn} {year}",
        )
        month_text = month_text.replace(
            extract_first(r'meta property="og:url" content="([^"]+)"', month_text, ""),
            f"https://jiujiu991.github.io{SITE_ROOT}archives/{year}/{month_str}/index.html",
        )
        month_text = month_text.replace(
            extract_first(r'<link rel="canonical" href="([^"]+)"', month_text, ""),
            f"https://jiujiu991.github.io{SITE_ROOT}archives/{year}/{month_str}/index.html",
        )
        month_item = build_archive_item(
            link=post_link,
            title=title,
            cover=cover_rel,
            publish_iso=publish_iso,
            publish_title=publish_title,
            publish_date=publish_date_str,
        )
        month_block = f'<div class="article-sort"><div class="article-sort-item year">{year}</div>{month_item}</div>'
        month_text = re.sub(r'<div class="article-sort">.*?</nav>', month_block + '<nav', month_text, flags=re.DOTALL)
        month_text = re.sub(r'(文章总览 - )\d+', r"\\g<1>1", month_text)
        if not args.dry_run:
            month_archive_path.parent.mkdir(parents=True, exist_ok=True)
            month_archive_path.write_text(month_text, encoding="utf-8")

    # Update search.xml
    search_path = REPO_ROOT / "search.xml"
    if search_path.exists():
        search_text = search_path.read_text(encoding="utf-8")
        search_text = update_search_xml(search_text, title, post_link, post_link, article_html)
        search_path.write_text(search_text, encoding="utf-8")

    # Update counts + timestamps across key pages
    if search_path.exists():
        total_posts = search_path.read_text(encoding="utf-8").count("<entry>")
    else:
        total_posts = 0

    # Update counts + timestamps across all html pages
    for p in REPO_ROOT.rglob("*.html"):
        html = p.read_text(encoding="utf-8")
        html = update_counts_and_dates(html, total_posts, update_time, last_push_iso)
        # Ensure archive list has the current month
        html = update_archive_list(
            html,
            month_link=f"{SITE_ROOT}archives/{year}/{month_str}/",
            month_label=f"{month_cn} {year}",
            count=1,
        )
        # Update archives index total
        if p.name == "index.html" and p.parent.name == "archives":
            html = re.sub(r'(文章总览 - )\d+', rf"\\g<1>{total_posts}", html)
        p.write_text(html, encoding="utf-8")

    print(f"OK: Generated {post_path}")
    print(f"Cover: {cover_rel}")
    if args.push and not args.dry_run:
        commit_msg = args.commit_message or f"Add {title}"
        subprocess.run(["git", "add", "-A"], cwd=str(REPO_ROOT), check=False)
        subprocess.run(["git", "commit", "-m", commit_msg], cwd=str(REPO_ROOT), check=False)
        subprocess.run(["git", "push"], cwd=str(REPO_ROOT), check=False)
        print("Git push: done.")
    else:
        print("Next steps:")
        print(f"  git add -A && git commit -m \"Add {title}\" && git push")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
